### ISSUE TITLE
 AttributeError: 'module' object has no attribute 'python'

### ISSUE THREAD

**Issue by xiaoyun4** [axelbrando/Mixture-Density-Networks-for-distribution-and-uncertainty-estimation#3]
when i try MDN-Introduction.ipynb
import tensorflow as tf
tf.python.control_flow_ops = tf

an error: 
AttributeError        Traceback (most recent call last)
<ipython-input-1-d2bd355e802f> in <module>()
      1 #Import of the TensorFlow and definition of the control_flow_ops variable
      2 import tensorflow as tf
----> 3 tf.python.control_flow_ops = tf
      4 
      5 #GPU Memory allocation on demand (Remove comments if necessary)

AttributeError: 'module' object has no attribute 'python'

the tensorflow version: 1.1.0-rc1;
keras version: 2.3.0

**Comment by axelbrando** [comment]
Hi Xiao,

On the one hand, the reason for doing this hack is, as explained in [[1]](http://stackoverflow.com/questions/40046619/keras-tensorflow-gives-the-error-no-attribute-control-flow-ops), [[2]](https://github.com/fchollet/keras/issues/3857), [[3]](http://stackoverflow.com/questions/39609724/tensorflow-control-flow-ops-not-working-good) avoiding an AttributeError that exist in the past with TensorFlow and Keras where the second one searched for an attribute called 'control_flow_ops' in the first one. I can not check it in this right moment but probably currently as I can deduce from [[4]](https://github.com/tensorflow/tensorflow/issues/7020) they corrected the bug and it is not necessary to perform this hack. Then, if you simply comment that line of code it is possible that it should work.

On the other hand, as I explained in the initial README, the code was tested on Keras (1.1.0) and TensorFlow (0.11.0rc2) so this may be the reason why it gives you problems running it with your different versions of Keras and TF.

Let me know if this small change solves your problem. Otherwise, we are in contact.

Axel

**Comment by xiaoyun4** [comment]
Thanks @axelbrando, it is exactly the different version of Keras and TF. I change the version: 

TF:0.12.0
keras: 1.0.0
 
and all is ok.

**Comment by GedeonGg** [comment]
hey i am having a problem with my code here.... while trying to print my pdf file in openerp i have this error popping up 'NON TYPE object has no attribute browse'... can someone help ?

**Comment by duhaime** [comment]
@GedeonGg if you are still having that problem I'd make a new issue or create a question on StackOverflow so you can get some help. This issue addresses a different topic (and is closed), so folks are unlikely to find your comment
